
services:
  python-app:
    build: .
    container_name: python-app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "5678:5678"  # debugpy port
    env_file:
      - .env
    # environment:
    #   MYSQL_HOST: database
    depends_on:
      database:
        condition: service_healthy
  database:
    ports:
      - "${EXPOSE_DB_PORT}:3306"
    image: "mysql:9.6"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  db_data:
